export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const OTP = 'OTP';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILD = 'OTP_FAILD';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const LOG_OUT = 'LOG_OUT';

export const GET_STORY_CATEGORIES = 'GET_STORY_CATEGORIES';
export const GET_STORY_CATEGORIES_SUCCESS = 'GET_STORY_CATEGORIES_SUCCESS';
export const GET_STORY_CATEGORIES_FAILED = 'GET_STORY_CATEGORIES_FAILED';

export const GET_STORY = 'GET_STORY';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY_FAILED = 'GET_STORY_FAILED';

export const SKIP_ONBOARDING = 'SKIP_ONBOARDING';
